feat: Add -DincludeScope=runtime to invocation request #3
DwcJava/dwcj-install-bbj-lib pull request #4
Opened 2024-01-18 15:34 UTC by kevinhagel

- code formatting
- Updated pom version to 0.1.9
- changed copy dependencies task to includeScope runtime here also.

2024-01-19 08:34 UTC, hyyan requested changes

2024-01-19 08:34 UTC, hyyan commented on pom.xml
> +    <version>0.1.9</version>
I don't believe we should combine updating versions with functionalities.

2024-01-19 08:34 UTC, hyyan commented on src/test/java/org/dwcj/installer/DwcjInstallerTest.java
> +package org.dwcj.installer;
This is an empty test file ?!

2024-01-19 08:34 UTC, hyyan commented on src/main/java/org/dwcj/installer/DwcjInstaller.java
> +            .addArg("-DincludeScope=runtime")
It would be better to use [`excludeScope` ](https://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html#excludeScope) to exclude test dependencies, as provided dependencies are desirable.

2024-01-19 08:40 UTC, StephanWald commented on src/main/java/org/dwcj/installer/DwcjInstaller.java
> +            .addArg("-DincludeScope=runtime")
howecer "provided" dependencies are still a missing piece in this process anyway. We don't POST the JARs for the "provided" dependencies, so they would need to be installed in the BBj-side system using some other way (like we do for the BBj dependencies when we develop in the engine). This is either a documentation issue, or we might want to further automate this so that the plug-in also sends over all the "provided" ones.

2024-01-19 09:06 UTC, StephanWald commented on src/main/java/org/dwcj/installer/DwcjInstaller.java
> +            .addArg("-DincludeScope=runtime")
somebody should create a separate issue with the "provided"

2024-01-19 09:22 UTC, hyyan commented on src/main/java/org/dwcj/installer/DwcjInstaller.java
> +            .addArg("-DincludeScope=runtime")
Opened #5

2024-01-19 10:46 UTC, kevinhagel commented on src/test/java/org/dwcj/installer/DwcjInstallerTest.java
> +package org.dwcj.installer;
a stub.

2024-01-19 10:49 UTC, kevinhagel commented on src/main/java/org/dwcj/installer/DwcjInstaller.java
> +            .addArg("-DincludeScope=runtime")
How is the maven dependency plugin inside DWCJ going to locate these provided dependencies?
In my experimental project I declare a libdir in my settings.xml, specifically for BBjAdminAPI.jar ... I like to see the source in some cases in my IDE.
This works in my dev environment, how is it going to work in the remote DWCJ environment?

2024-01-19 10:52 UTC, hyyan commented on src/test/java/org/dwcj/installer/DwcjInstallerTest.java
> +package org.dwcj.installer;
It should be removed

2024-01-19 10:53 UTC, kevinhagel commented on src/main/java/org/dwcj/installer/DwcjInstaller.java
> +            .addArg("-DincludeScope=runtime")
From the docs on exclude scope:

> runtime exclude scope excludes runtime and compile dependencies,
> compile exclude scope excludes compile, provided, and system dependencies,
> test exclude scope excludes all dependencies, then not really a legitimate option: it will fail, you probably meant to configure includeScope = compile
> provided exclude scope just excludes provided dependencies,
> system exclude scope just excludes system dependencies.

compile exclude scope will include the test dependencies.  I tested it.

2024-01-19 10:53 UTC, hyyan commented on src/main/java/org/dwcj/installer/DwcjInstaller.java
> +            .addArg("-DincludeScope=runtime")
I believe the developer may need to add certain configurations to instruct the plugin on where to retrieve the jars from.

2024-01-19 11:18 UTC, hyyan commented on src/main/java/org/dwcj/installer/DwcjInstaller.java
> +            .addArg("-DincludeScope=runtime")
@kevinhagel I believe issue #5 warrants separate attention. For the current matter, setting `includeScope=runtime` is appropriate. We can switch it to `compile` once issue #5 has been resolved.

2024-01-19 11:26 UTC, kevinhagel commented on src/main/java/org/dwcj/installer/DwcjInstaller.java
> +            .addArg("-DincludeScope=runtime")
If in dwcj-install-bbj-lib I change the includeScope=compile it will include systemScope and provided scope.  I've tested this.   my BBjAdminAPI.jar in system scope, and i just added commons-io to my project and declared it provided scope.  Both of them show up in the deployment

2024-01-19 11:34 UTC, kevinhagel commented on src/test/java/org/dwcj/installer/DwcjInstallerTest.java
> +package org.dwcj.installer;
I'm going to add a couple of tests to it today.  These are tricky for this kind of file system stuff.

2024-01-22 08:42 UTC, hyyan commented on src/test/java/org/dwcj/installer/DwcjInstallerTest.java
> +package org.dwcj.installer;
@kevinhagel let us know when you are done with this, The current PR looks good to me

2024-01-22 09:06 UTC, hyyan commented
After Kevin completes his changes, @MatthewHawkins, could you also test this locally to make sure nothing is broken?

2024-01-22 09:21 UTC, hyyan approved these changes

2024-01-22 11:53 UTC, MatthewHawkins approved these changes
Tested - works great!

2024-01-22 13:30 UTC, merged